@startuml

entity 用户
entity 一级分类
entity 二级分类
entity 频道
entity 文章
entity 笔记
entity 句子

entity 词书
entity 单词

一级分类 -- 二级分类 : 包含
二级分类 -- 频道 : 包含
频道 -- 文章 : 包含
文章 -- 句子 : 包含
用户 -- 文章 : 学习
用户 -- 文章 : 收藏
用户 -- 频道 : 收藏
用户 -- 笔记 : 记
笔记 -- 文章 : 包含

词书 -- 单词 : 学习
用户 -- 单词 : 收藏

@enduml
