@startuml
left to right direction
skinparam packageStyle rectangle
actor 管理员
actor 超级管理员
rectangle 用户管理模块 {
  管理员 --> (用户管理)
  (用户管理) ..> (查看用户) : <<include>>
  (用户管理) ..> (重置用户密码) : <<include>>
  (用户管理) ..> (冻结用户) : <<include>>
  (用户管理) ..> (解冻用户) : <<include>>
  超级管理员 --> (用户管理)
  超级管理员 --> (管理员管理)
  (管理员管理) ..> (查看管理员) : <<include>>
  (管理员管理) ..> (添加管理员) : <<include>>
  (管理员管理) ..> (删除管理员) : <<include>>
  管理员 --> (反馈管理)
  超级管理员 --> (反馈管理)
  (反馈管理) ..> (查看反馈) : <<include>>
  (反馈管理) ..> (处理反馈) : <<include>>
  (反馈管理) ..> (回复消息) : <<include>>
  管理员 --> (个人管理)
  超级管理员 --> (个人管理)
  (个人管理) ..> (登录) : <<include>>
  (个人管理) ..> (查看个人信息) : <<include>>
  (个人管理) ..> (修改个人信息) : <<include>>
  (个人管理) ..> (修改密码) : <<include>>
}
@enduml
