@startuml
left to right direction
skinparam packageStyle rectangle
actor User
rectangle 知识学习模块 {
  User --> (轮播图)
  User --> (热门推荐)
  User --> (最近更新)
  User --> (分类)
  User --> (搜索)
  User --> (频道)
  (频道) ..> (查看频道详情) : <<include>>
  (频道) ..> (查看文章目录) : <<include>>
  (频道) ..> (切换文章目录排序) : <<include>>
  (频道) ..> (订阅频道) : <<include>>
  User --> (文章)
  (文章) ..> (分享文章) : <<include>>
  (文章) ..> (收藏文章) : <<include>>
  (文章) ..> (查看所属频道) : <<include>>
  (文章) ..> (添加文章笔记) : <<include>>
  (文章) ..> (阅读模式) : <<include>>
  (阅读模式) ..> (阅读英文文章) : <<include>>
  (文章) ..> (听力模式) : <<include>>
  (听力模式) ..> (关闭/开启定位) : <<include>>
  (听力模式) ..> (拖动进度) : <<include>>
  (听力模式) ..> (切换播放倍速) : <<include>>
  (听力模式) ..> (切换中英显示模式) : <<include>>
  (切换中英显示模式) ..> (全部隐藏) : <<include>>
  (切换中英显示模式) ..> (点击显示译文) : <<include>>
  (切换中英显示模式) ..> (只显示译文) : <<include>>
  (切换中英显示模式) ..> (只显示原文) : <<include>>
  (切换中英显示模式) ..> (双语显示) : <<include>>
  (听力模式) ..> (播放视频) : <<include>>
  (听力模式) ..> (播放音频) : <<include>>
  User --> (背单词)
  (背单词) ..> (选择词书) : <<include>>
  (选择词书) <.. (查看单词列表) : <<extend>>
  (背单词) ..> (背词设置) : <<include>>
  (背词设置) ..> (设置每组词数) : <<include>>
  (背词设置) ..> (设置每日计划) : <<include>>
  (背单词) ..> (复习单词) : <<include>>
  (学习单词) ..> (选择认识情况) : <<include>>
  (学习单词) ..> (播放发音) : <<include>>
  (学习单词) ..> (单词详情) : <<include>>
  (背单词) ..> (学习单词) : <<include>>
  (复习单词) .u.> (选择认识情况) : <<include>>
  (复习单词) .u.> (播放发音) : <<include>>
  (复习单词) .u.> (单词详情) : <<include>>
}
@enduml
