@startuml
start
:选择做题方式;
if ("是否选择专项训练？") then (是)
  :选择题目类型;
  :进入专项训练;
elseif ("是否选择历年真题？") then (是)
  :选择历年真题年份;
  :进入历年真题;
elseif ("是否选择模拟考试？") then (是)
  :选择模拟考试试卷;
  :进入模拟考试;
else (否)
  :进入题库选择;
endif
:选择题库;
:进入题目界面;
while ("题目是否作答完成？") is (否)
  :回答题目;
endwhile
:提交试卷;
:显示测试报告;
:查看解析;
stop
@enduml
